#! /bin/bash

npm install -g gulp-eslint
npm install -g gulp-include
npm install -g gulp-sass
npm install -g gulp-autoprefixer
npm install -g gulp-clean-css
npm install -g gulp-rename
npm install -g gulp-uglify
npm install -g gulp
