#! /bin/bash
#refactor this at some point

if [[ -d "node_modules/foundation-sites" && -d "node_modules/font-awesome" && -d "node_modules/what-input" ]]; then
  if [[ ! -d "src/styles/vendor" || ! -d "src/scripts/vendor" ]]; then
    #copy foundation scss files
    mkdir -p src/styles/vendor/foundation
    cp -r node_modules/foundation-sites/scss src/styles/vendor/foundation/scss
    cp -r node_modules/foundation-sites/_vendor src/styles/vendor/foundation/_vendor
    #copy foundation js files
    mkdir -p src/scripts/vendor/foundation
    cp -r node_modules/foundation-sites/dist/js src/scripts/vendor/foundation/js
    #copy font-awesome files
    mkdir -p assets/fonts
    mkdir -p src/styles/vendor/font-awesome
    cp -r node_modules/font-awesome/scss src/styles/vendor/font-awesome/scss
    cp -r node_modules/font-awesome/fonts/. assets/fonts
    #copy what-input files
    mkdir -p src/scripts/vendor/what-input/js
    cp node_modules/what-input/dist/what-input.min.js src/scripts/vendor/what-input/js/what-input.min.js
    #space saver
    rm -rf node_modules/foundation-sites
    rm -rf node_modules/font-awesome
    rm -rf node_modules/jquery
    rm -rf node_modules/what-input
  else
    #oops! start over
    rm -rf assets/fonts
    rm -rf src/scripts/vendor
    rm -rf src/styles/vendor
    echo "Please re-run 'preen'"
  fi
else
  #oops! start over
  rm -rf node_modules/foundation-sites
  rm -rf node_modules/font-awesome
  rm -rf node_modules/jquery
  rm -rf node_modules/what-input
  echo "Please re-run 'npm install --production'"
fi